# Generated by Django 5.2.4 on 2025-11-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Computed discount amount based on total and rate.', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount applied based on type.', max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(choices=[('regular', 'Regular Customer'), ('pwd', 'Person with Disability (PWD)'), ('senior', 'Senior Citizen'), ('other', 'Other Discount')], default='regular', help_text='Type of discount applied to the sale.', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final amount after discount is applied.', max_digits=10),
        ),
    ]
