# Generated by Django 5.2.4 on 2025-11-11 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sale_discount_amount_sale_discount_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_base_price', models.DecimalField(decimal_places=2, help_text='Previous base price before change', max_digits=10)),
                ('new_base_price', models.DecimalField(decimal_places=2, help_text='New base price after change', max_digits=10)),
                ('old_selling_price', models.DecimalField(decimal_places=2, help_text='Previous selling price before change', max_digits=10)),
                ('new_selling_price', models.DecimalField(decimal_places=2, help_text='New selling price after change', max_digits=10)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for price change', null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='base.medicine')),
            ],
            options={
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-change_date'],
            },
        ),
    ]
