# Generated by Django 5.2.4 on 2025-11-13 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pricehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DosageForm',
        ),
        migrations.AddField(
            model_name='medicine',
            name='product_type',
            field=models.ForeignKey(blank=True, help_text='Product type within the selected category', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='base.producttype'),
        ),
    ]
