# Generated by Django 5.2.4 on 2025-11-14 06:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_add_product_type_remove_dosageform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of role permissions and responsibilities', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_number', models.CharField(blank=True, help_text='Unique employee identifier (e.g., EMP-001)', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(help_text='Linked Django User account', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employee_number', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDesignation',
            fields=[
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('is_primary', models.BooleanField(default=True, help_text='Primary role for this employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='base.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_designations', to='base.role')),
            ],
            options={
                'verbose_name': 'Employee Designation',
                'verbose_name_plural': 'Employee Designations',
                'ordering': ['-is_primary', 'assigned_date'],
                'unique_together': {('employee', 'role')},
            },
        ),
    ]
