# Generated by Django 5.2.4 on 2025-11-14 06:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_role_employee_employeedesignation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('discount_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_name', models.CharField(help_text='Name of discount (e.g., PWD, Senior Citizen, Regular)', max_length=100, unique=True)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount rate (e.g., 20.00 for 20%)', max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this discount type is currently available')),
                ('requires_id', models.BooleanField(default=False, help_text='Whether this discount requires ID verification (e.g., PWD, Senior)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discount Type',
                'verbose_name_plural': 'Discount Types',
                'ordering': ['discount_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(help_text='Payment method name (e.g., Cash, Credit Card, GCash)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is currently available')),
                ('requires_reference', models.BooleanField(default=False, help_text='Whether this payment method requires a reference number (e.g., card transactions)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['method_name'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refund_id', models.AutoField(primary_key=True, serialize=False)),
                ('refund_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_refunded', models.DecimalField(decimal_places=2, help_text='Amount returned to customer', max_digits=10)),
                ('reason', models.CharField(choices=[('expired', 'Expired Product'), ('damaged', 'Damaged Product'), ('wrong_item', 'Wrong Item Sold'), ('customer_request', 'Customer Request'), ('overcharge', 'Overcharge/Pricing Error'), ('other', 'Other Reason')], help_text='Reason for refund', max_length=50)),
                ('reason_details', models.TextField(blank=True, help_text='Additional details about the refund', null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Reference number for refund transaction', max_length=100, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager who approved the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, help_text='Method used for refund (usually same as original payment)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.paymentmethod')),
                ('processed_by', models.ForeignKey(help_text='User who processed the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(help_text='Original sale being refunded', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='base.sale')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-refund_date'],
            },
        ),
    ]
