# Generated by Django 5.2.4 on 2025-11-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_discounttype_paymentmethod_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount tendered by customer', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Change returned to customer', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_type_fk',
            field=models.ForeignKey(blank=True, help_text='Configured discount type applied', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.discounttype'),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Printable invoice number', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Payment method used', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.paymentmethod'),
        ),
    ]
