# Generated by Django 5.2.4 on 2025-11-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_map_legacy_discount_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount_type',
        ),
    ]
