# Generated by Django 5.2.4 on 2025-11-14 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_sale_discount_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RefundLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded_quantity', models.PositiveIntegerField(help_text='Quantity refunded from this movement')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_lines', to='base.stockmovement')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='base.refund')),
            ],
            options={
                'verbose_name': 'Refund Line',
                'verbose_name_plural': 'Refund Lines',
            },
        ),
    ]
