# Generated by Django 5.2.4 on 2025-11-14 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_refund_approved_date_refund_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before discount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity in pieces'),
        ),
        migrations.CreateModel(
            name='SaleLineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity in selected unit type (box/pack/piece)')),
                ('unit_type', models.CharField(choices=[('piece', 'Piece'), ('pack', 'Pack'), ('box', 'Box')], default='piece', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per single piece (always stored as per-piece price)', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total for this line: quantity (in pieces) × unit_price', max_digits=10)),
                ('pieces_dispensed', models.PositiveIntegerField(default=0, help_text='Total pieces dispensed (quantity converted to pieces)')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='base.medicine')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='base.sale')),
            ],
            options={
                'ordering': ['line_item_id'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='base.salelineitem'),
        ),
    ]
