# Generated by Django 5.2.8 on 2025-11-14 09:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_sale_total_amount_alter_stockmovement_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('ordering_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text='Customer name for the order', max_length=255)),
                ('customer_contact', models.CharField(blank=True, help_text='Phone number or contact info', max_length=100, null=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the order was placed')),
                ('expected_pickup_date', models.DateField(blank=True, help_text='When customer expects to pick up', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending - Not Yet Confirmed'), ('Confirmed', 'Confirmed - Items Reserved'), ('Ready', 'Ready for Pickup'), ('Completed', 'Completed - Picked Up and Paid'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Current order status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes', null=True)),
                ('confirmed_date', models.DateTimeField(blank=True, help_text='When order was confirmed', null=True)),
                ('completed_date', models.DateTimeField(blank=True, help_text='When order was completed', null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Staff who confirmed the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_orders', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(blank=True, help_text='Sale record when order is completed and paid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_order', to='base.sale')),
                ('user', models.ForeignKey(help_text='Staff member who created the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Order',
                'verbose_name_plural': 'Customer Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('ordered_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_type', models.CharField(choices=[('piece', 'Piece'), ('pack', 'Pack'), ('box', 'Box')], default='piece', help_text='Unit type for ordering', max_length=10)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity in selected unit type')),
                ('pieces_needed', models.PositiveIntegerField(default=0, help_text='Total pieces needed (calculated from quantity and unit_type)')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per piece at time of order', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text='Total for this line item', max_digits=10)),
                ('batch', models.ForeignKey(blank=True, help_text='Specific batch if reserved (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_items', to='base.stockbatch')),
                ('medicine', models.ForeignKey(help_text='Product being ordered', on_delete=django.db.models.deletion.PROTECT, related_name='ordered_items', to='base.medicine')),
                ('ordering', models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='base.ordering')),
            ],
            options={
                'verbose_name': 'Ordered Product',
                'verbose_name_plural': 'Ordered Products',
                'ordering': ['ordered_product_id'],
            },
        ),
    ]
