# Generated by Django 5.2.4 on 2025-11-14 09:55

from django.db import migrations


def remove_unused_discount_types(apps, schema_editor):
    """Remove 'Regular Customer' and 'Other Discount' types as they are no longer needed."""
    DiscountType = apps.get_model('base', 'DiscountType')
    
    # Delete Regular Customer and Other Discount types
    DiscountType.objects.filter(discount_name__in=['Regular Customer', 'Other Discount']).delete()
    print("Removed unused discount types: Regular Customer and Other Discount")


def reverse_add_discount_types(apps, schema_editor):
    """Reverse migration: Recreate the removed discount types."""
    DiscountType = apps.get_model('base', 'DiscountType')
    
    # Recreate the removed discount types
    DiscountType.objects.get_or_create(
        discount_name='Regular Customer',
        defaults={
            'discount_rate': 0,
            'description': 'No discount applied',
            'requires_id': False
        }
    )
    DiscountType.objects.get_or_create(
        discount_name='Other Discount',
        defaults={
            'discount_rate': 10,
            'description': 'Other promotional or special discounts',
            'requires_id': False
        }
    )
    print("Recreated discount types: Regular Customer and Other Discount")


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_ordering_orderedproduct'),
    ]

    operations = [
        migrations.RunPython(remove_unused_discount_types, reverse_add_discount_types),
    ]
